[build]
  publish = "cnhluizcdd-main"
  command = ""

[[redirects]]
  from = "/*"
  to = "/onhugbahtochnow.sbs/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"